### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by zabbal** [sancus-tee/sancus-compiler#34]
What's the license for code in this repo?

**Comment by fritzalder** [comment]
Hi and sorry for this late response. We have been discussing this question internally and have not come to a conclusion yet. We will update the license on the repo once we are done with the discussion and I will also write into this issue to notify you. 

However, we will probably decide on some form of open-source license that allows use for academic and non-commercial use. Feel free to throw me an email if you want to ask a specific question regarding licensing before we put out a proper license.

**Comment by fritzalder** [comment]
Hey, this is a very late update but maybe interesting to you: We just added a Licence clarification to all of our Sancus repositories. Feel free to open a new issue if you are still interested or if we missed something :)
